/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type AckAlertRequest = {
  by: string;
  note?: string | undefined;
};

/** @internal */
export type AckAlertRequest$Outbound = {
  by: string;
  note?: string | undefined;
};

/** @internal */
export const AckAlertRequest$outboundSchema: z.ZodType<
  AckAlertRequest$Outbound,
  z.ZodTypeDef,
  AckAlertRequest
> = z.object({
  by: z.string(),
  note: z.string().optional(),
});

export function ackAlertRequestToJSON(
  ackAlertRequest: AckAlertRequest,
): string {
  return JSON.stringify(AckAlertRequest$outboundSchema.parse(ackAlertRequest));
}
