/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

/**
 * Mute an alert's notifications until `until` (which must be in the future).
 */
export type SnoozeAlertRequest = {
  by: string;
  note?: string | undefined;
  until: Date;
};

/** @internal */
export type SnoozeAlertRequest$Outbound = {
  by: string;
  note?: string | undefined;
  until: string;
};

/** @internal */
export const SnoozeAlertRequest$outboundSchema: z.ZodType<
  SnoozeAlertRequest$Outbound,
  z.ZodTypeDef,
  SnoozeAlertRequest
> = z.object({
  by: z.string(),
  note: z.string().optional(),
  until: z.date().transform(v => v.toISOString()),
});

export function snoozeAlertRequestToJSON(
  snoozeAlertRequest: SnoozeAlertRequest,
): string {
  return JSON.stringify(
    SnoozeAlertRequest$outboundSchema.parse(snoozeAlertRequest),
  );
}
