/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  BankAccountRelatedAccounts,
  BankAccountRelatedAccounts$inboundSchema,
} from "./bankaccountrelatedaccounts.js";

export type BankAccount = {
  bankAccountMetadata?: { [k: string]: string } | null | undefined;
  accountID?: string | undefined;
  accountNumber?: string | undefined;
  connectorID?: string | undefined;
  country: string;
  createdAt: Date;
  iban?: string | undefined;
  id: string;
  name: string;
  provider?: string | undefined;
  relatedAccounts?: Array<BankAccountRelatedAccounts> | undefined;
  swiftBicCode?: string | undefined;
};

/** @internal */
export const BankAccount$inboundSchema: z.ZodType<
  BankAccount,
  z.ZodTypeDef,
  unknown
> = z.object({
  metadata: z.nullable(z.record(z.string())).optional(),
  accountID: z.string().optional(),
  accountNumber: z.string().optional(),
  connectorID: z.string().optional(),
  country: z.string(),
  createdAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  iban: z.string().optional(),
  id: z.string(),
  name: z.string(),
  provider: z.string().optional(),
  relatedAccounts: z.array(BankAccountRelatedAccounts$inboundSchema).optional(),
  swiftBicCode: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "metadata": "bankAccountMetadata",
  });
});

export function bankAccountFromJSON(
  jsonString: string,
): SafeParseResult<BankAccount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BankAccount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BankAccount' from JSON`,
  );
}
