/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { PaymentStatus, PaymentStatus$inboundSchema } from "./paymentstatus.js";

export type PaymentAdjustment = {
  amount: bigint;
  createdAt: Date;
  raw: { [k: string]: any };
  reference: string;
  status: PaymentStatus;
};

/** @internal */
export const PaymentAdjustment$inboundSchema: z.ZodType<
  PaymentAdjustment,
  z.ZodTypeDef,
  unknown
> = z.object({
  amount: z.number().transform(v => BigInt(v)),
  createdAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  raw: z.record(z.any()),
  reference: z.string(),
  status: PaymentStatus$inboundSchema,
});

export function paymentAdjustmentFromJSON(
  jsonString: string,
): SafeParseResult<PaymentAdjustment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentAdjustment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentAdjustment' from JSON`,
  );
}
