/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export const PoolTypeEnum = {
  Static: "STATIC",
  Dynamic: "DYNAMIC",
} as const;
export type PoolTypeEnum = ClosedEnum<typeof PoolTypeEnum>;

/** @internal */
export const PoolTypeEnum$inboundSchema: z.ZodNativeEnum<typeof PoolTypeEnum> =
  z.nativeEnum(PoolTypeEnum);
