/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Pool, Pool$inboundSchema } from "./pool.js";

/**
 * Paginated cursor wrapping the list of pools
 */
export type PoolsCursorCursor = {
  data: Array<Pool>;
  /**
   * Whether further pages are available
   */
  hasMore: boolean;
  /**
   * Cursor for the next page, absent on the last page
   */
  next?: string | undefined;
  /**
   * Number of items requested per page
   */
  pageSize: number;
  /**
   * Cursor for the previous page, absent on the first page
   */
  previous?: string | undefined;
};

/**
 * OK
 */
export type PoolsCursor = {
  /**
   * Paginated cursor wrapping the list of pools
   */
  cursor: PoolsCursorCursor;
};

/** @internal */
export const PoolsCursorCursor$inboundSchema: z.ZodType<
  PoolsCursorCursor,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(Pool$inboundSchema),
  hasMore: z.boolean(),
  next: z.string().optional(),
  pageSize: z.number().int(),
  previous: z.string().optional(),
});

export function poolsCursorCursorFromJSON(
  jsonString: string,
): SafeParseResult<PoolsCursorCursor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PoolsCursorCursor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PoolsCursorCursor' from JSON`,
  );
}

/** @internal */
export const PoolsCursor$inboundSchema: z.ZodType<
  PoolsCursor,
  z.ZodTypeDef,
  unknown
> = z.object({
  cursor: z.lazy(() => PoolsCursorCursor$inboundSchema),
});

export function poolsCursorFromJSON(
  jsonString: string,
): SafeParseResult<PoolsCursor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PoolsCursor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PoolsCursor' from JSON`,
  );
}
