/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V3CreateBankAccountResponse = {
  /**
   * The ID of the created bank account
   */
  data: string;
};

/** @internal */
export const V3CreateBankAccountResponse$inboundSchema: z.ZodType<
  V3CreateBankAccountResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.string(),
});

export function v3CreateBankAccountResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3CreateBankAccountResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3CreateBankAccountResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3CreateBankAccountResponse' from JSON`,
  );
}
