/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { V3Address, V3Address$inboundSchema } from "./v3address.js";
import {
  V3ContactDetails,
  V3ContactDetails$inboundSchema,
} from "./v3contactdetails.js";

/**
 * An end user on whose behalf payments and open banking connections are made
 */
export type V3PaymentServiceUser = {
  /**
   * A postal address
   */
  address?: V3Address | undefined;
  /**
   * Bank accounts associated with the user
   */
  bankAccountIDs?: Array<string> | null | undefined;
  /**
   * How to reach a payment service user
   */
  contactDetails?: V3ContactDetails | undefined;
  /**
   * When the user was registered
   */
  createdAt: Date;
  /**
   * Unique identifier of the payment service user
   */
  id: string;
  /**
   * Arbitrary key/value pairs attached to the resource
   */
  metadata?: { [k: string]: string } | null | undefined;
  /**
   * Full name of the payment service user
   */
  name: string;
};

/** @internal */
export const V3PaymentServiceUser$inboundSchema: z.ZodType<
  V3PaymentServiceUser,
  z.ZodTypeDef,
  unknown
> = z.object({
  address: V3Address$inboundSchema.optional(),
  bankAccountIDs: z.nullable(z.array(z.string())).optional(),
  contactDetails: V3ContactDetails$inboundSchema.optional(),
  createdAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  id: z.string(),
  metadata: z.nullable(z.record(z.string())).optional(),
  name: z.string(),
});

export function v3PaymentServiceUserFromJSON(
  jsonString: string,
): SafeParseResult<V3PaymentServiceUser, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3PaymentServiceUser$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3PaymentServiceUser' from JSON`,
  );
}
