/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V3TinkConfig = {
  clientID: string;
  clientSecret: string;
  endpoint: string;
  name: string;
  /**
   * @deprecated field: From v3.1, this parameter will be ignored.
   */
  pageSize?: number | undefined;
  pollingPeriod?: string | undefined;
  provider: "Tink";
};

/** @internal */
export const V3TinkConfig$inboundSchema: z.ZodType<
  V3TinkConfig,
  z.ZodTypeDef,
  unknown
> = z.object({
  clientID: z.string(),
  clientSecret: z.string(),
  endpoint: z.string(),
  name: z.string(),
  pageSize: z.number().int().default(25),
  pollingPeriod: z.string().default("30m"),
  provider: z.literal("Tink"),
});
/** @internal */
export type V3TinkConfig$Outbound = {
  clientID: string;
  clientSecret: string;
  endpoint: string;
  name: string;
  pageSize: number;
  pollingPeriod: string;
  provider: "Tink";
};

/** @internal */
export const V3TinkConfig$outboundSchema: z.ZodType<
  V3TinkConfig$Outbound,
  z.ZodTypeDef,
  V3TinkConfig
> = z.object({
  clientID: z.string(),
  clientSecret: z.string(),
  endpoint: z.string(),
  name: z.string(),
  pageSize: z.number().int().default(25),
  pollingPeriod: z.string().default("30m"),
  provider: z.literal("Tink"),
});

export function v3TinkConfigToJSON(v3TinkConfig: V3TinkConfig): string {
  return JSON.stringify(V3TinkConfig$outboundSchema.parse(v3TinkConfig));
}
export function v3TinkConfigFromJSON(
  jsonString: string,
): SafeParseResult<V3TinkConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3TinkConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3TinkConfig' from JSON`,
  );
}
