/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";

export type V3UpdateBankAccountMetadataRequest = {
  v3Metadata: { [k: string]: string } | null;
};

/** @internal */
export type V3UpdateBankAccountMetadataRequest$Outbound = {
  metadata: { [k: string]: string } | null;
};

/** @internal */
export const V3UpdateBankAccountMetadataRequest$outboundSchema: z.ZodType<
  V3UpdateBankAccountMetadataRequest$Outbound,
  z.ZodTypeDef,
  V3UpdateBankAccountMetadataRequest
> = z.object({
  v3Metadata: z.nullable(z.record(z.string())),
}).transform((v) => {
  return remap$(v, {
    v3Metadata: "metadata",
  });
});

export function v3UpdateBankAccountMetadataRequestToJSON(
  v3UpdateBankAccountMetadataRequest: V3UpdateBankAccountMetadataRequest,
): string {
  return JSON.stringify(
    V3UpdateBankAccountMetadataRequest$outboundSchema.parse(
      v3UpdateBankAccountMetadataRequest,
    ),
  );
}
