// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

type ErrorResponse struct {
	Details      *string               `json:"details,omitempty"`
	ErrorCode    components.ErrorsEnum `json:"errorCode"`
	ErrorMessage string                `json:"errorMessage"`
}

var _ error = &ErrorResponse{}

func (e *ErrorResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
