/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  Account,
  Account$inboundSchema,
  Account$Outbound,
  Account$outboundSchema,
} from "./account.js";

export type Cursor = {
  data: Array<Account>;
  hasMore: boolean;
  next?: string | undefined;
  pageSize: number;
  previous?: string | undefined;
};

export type AccountsCursorResponse = {
  cursor: Cursor;
};

/** @internal */
export const Cursor$inboundSchema: z.ZodType<Cursor, z.ZodTypeDef, unknown> = z
  .object({
    data: z.array(Account$inboundSchema),
    hasMore: z.boolean(),
    next: z.string().optional(),
    pageSize: z.number().int(),
    previous: z.string().optional(),
  });

/** @internal */
export type Cursor$Outbound = {
  data: Array<Account$Outbound>;
  hasMore: boolean;
  next?: string | undefined;
  pageSize: number;
  previous?: string | undefined;
};

/** @internal */
export const Cursor$outboundSchema: z.ZodType<
  Cursor$Outbound,
  z.ZodTypeDef,
  Cursor
> = z.object({
  data: z.array(Account$outboundSchema),
  hasMore: z.boolean(),
  next: z.string().optional(),
  pageSize: z.number().int(),
  previous: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Cursor$ {
  /** @deprecated use `Cursor$inboundSchema` instead. */
  export const inboundSchema = Cursor$inboundSchema;
  /** @deprecated use `Cursor$outboundSchema` instead. */
  export const outboundSchema = Cursor$outboundSchema;
  /** @deprecated use `Cursor$Outbound` instead. */
  export type Outbound = Cursor$Outbound;
}

/** @internal */
export const AccountsCursorResponse$inboundSchema: z.ZodType<
  AccountsCursorResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  cursor: z.lazy(() => Cursor$inboundSchema),
});

/** @internal */
export type AccountsCursorResponse$Outbound = {
  cursor: Cursor$Outbound;
};

/** @internal */
export const AccountsCursorResponse$outboundSchema: z.ZodType<
  AccountsCursorResponse$Outbound,
  z.ZodTypeDef,
  AccountsCursorResponse
> = z.object({
  cursor: z.lazy(() => Cursor$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AccountsCursorResponse$ {
  /** @deprecated use `AccountsCursorResponse$inboundSchema` instead. */
  export const inboundSchema = AccountsCursorResponse$inboundSchema;
  /** @deprecated use `AccountsCursorResponse$outboundSchema` instead. */
  export const outboundSchema = AccountsCursorResponse$outboundSchema;
  /** @deprecated use `AccountsCursorResponse$Outbound` instead. */
  export type Outbound = AccountsCursorResponse$Outbound;
}
