/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ActivityRevertTransaction = {
  id: string;
  ledger: string;
};

/** @internal */
export const ActivityRevertTransaction$inboundSchema: z.ZodType<
  ActivityRevertTransaction,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  ledger: z.string(),
});

export function activityRevertTransactionFromJSON(
  jsonString: string,
): SafeParseResult<ActivityRevertTransaction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActivityRevertTransaction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActivityRevertTransaction' from JSON`,
  );
}
