/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { OrchestrationTransaction, OrchestrationTransaction$ } from "./orchestrationtransaction";
import * as z from "zod";

export type ActivityRevertTransactionOutput = {
    data: OrchestrationTransaction;
};

/** @internal */
export namespace ActivityRevertTransactionOutput$ {
    export type Inbound = {
        data: OrchestrationTransaction$.Inbound;
    };

    export const inboundSchema: z.ZodType<ActivityRevertTransactionOutput, z.ZodTypeDef, Inbound> =
        z
            .object({
                data: OrchestrationTransaction$.inboundSchema,
            })
            .transform((v) => {
                return {
                    data: v.data,
                };
            });

    export type Outbound = {
        data: OrchestrationTransaction$.Outbound;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        ActivityRevertTransactionOutput
    > = z
        .object({
            data: OrchestrationTransaction$.outboundSchema,
        })
        .transform((v) => {
            return {
                data: v.data,
            };
        });
}
