/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AggregateBalancesResponse = {
  data: { [k: string]: number };
};

/** @internal */
export const AggregateBalancesResponse$inboundSchema: z.ZodType<
  AggregateBalancesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.record(z.number().int()),
});

/** @internal */
export type AggregateBalancesResponse$Outbound = {
  data: { [k: string]: number };
};

/** @internal */
export const AggregateBalancesResponse$outboundSchema: z.ZodType<
  AggregateBalancesResponse$Outbound,
  z.ZodTypeDef,
  AggregateBalancesResponse
> = z.object({
  data: z.record(z.number().int()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AggregateBalancesResponse$ {
  /** @deprecated use `AggregateBalancesResponse$inboundSchema` instead. */
  export const inboundSchema = AggregateBalancesResponse$inboundSchema;
  /** @deprecated use `AggregateBalancesResponse$outboundSchema` instead. */
  export const outboundSchema = AggregateBalancesResponse$outboundSchema;
  /** @deprecated use `AggregateBalancesResponse$Outbound` instead. */
  export type Outbound = AggregateBalancesResponse$Outbound;
}

export function aggregateBalancesResponseToJSON(
  aggregateBalancesResponse: AggregateBalancesResponse,
): string {
  return JSON.stringify(
    AggregateBalancesResponse$outboundSchema.parse(aggregateBalancesResponse),
  );
}

export function aggregateBalancesResponseFromJSON(
  jsonString: string,
): SafeParseResult<AggregateBalancesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AggregateBalancesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AggregateBalancesResponse' from JSON`,
  );
}
