/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { BankAccount, BankAccount$inboundSchema } from "./bankaccount.js";

/**
 * OK
 */
export type BankAccountResponse = {
  data: BankAccount;
};

/** @internal */
export const BankAccountResponse$inboundSchema: z.ZodType<
  BankAccountResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: BankAccount$inboundSchema,
});

export function bankAccountResponseFromJSON(
  jsonString: string,
): SafeParseResult<BankAccountResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BankAccountResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BankAccountResponse' from JSON`,
  );
}
