/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type BankAccountRequest = {
  accountNumber?: string | undefined;
  connectorID?: string | undefined;
  country: string;
  iban?: string | undefined;
  metadata?: { [k: string]: string } | null | undefined;
  name: string;
  swiftBicCode?: string | undefined;
};

/** @internal */
export type BankAccountRequest$Outbound = {
  accountNumber?: string | undefined;
  connectorID?: string | undefined;
  country: string;
  iban?: string | undefined;
  metadata?: { [k: string]: string } | null | undefined;
  name: string;
  swiftBicCode?: string | undefined;
};

/** @internal */
export const BankAccountRequest$outboundSchema: z.ZodType<
  BankAccountRequest$Outbound,
  z.ZodTypeDef,
  BankAccountRequest
> = z.object({
  accountNumber: z.string().optional(),
  connectorID: z.string().optional(),
  country: z.string(),
  iban: z.string().optional(),
  metadata: z.nullable(z.record(z.string())).optional(),
  name: z.string(),
  swiftBicCode: z.string().optional(),
});

export function bankAccountRequestToJSON(
  bankAccountRequest: BankAccountRequest,
): string {
  return JSON.stringify(
    BankAccountRequest$outboundSchema.parse(bankAccountRequest),
  );
}
