/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type Data = {
    connectorID: string;
};

export type ConnectorResponse = {
    data: Data;
};

/** @internal */
export namespace Data$ {
    export const inboundSchema: z.ZodType<Data, z.ZodTypeDef, unknown> = z.object({
        connectorID: z.string(),
    });

    export type Outbound = {
        connectorID: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Data> = z.object({
        connectorID: z.string(),
    });
}

/** @internal */
export namespace ConnectorResponse$ {
    export const inboundSchema: z.ZodType<ConnectorResponse, z.ZodTypeDef, unknown> = z.object({
        data: z.lazy(() => Data$.inboundSchema),
    });

    export type Outbound = {
        data: Data$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ConnectorResponse> = z.object({
        data: z.lazy(() => Data$.outboundSchema),
    });
}
