/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AdyenConfig,
  AdyenConfig$inboundSchema,
  AdyenConfig$Outbound,
  AdyenConfig$outboundSchema,
} from "./adyenconfig.js";
import {
  AtlarConfig,
  AtlarConfig$inboundSchema,
  AtlarConfig$Outbound,
  AtlarConfig$outboundSchema,
} from "./atlarconfig.js";
import {
  BankingCircleConfig,
  BankingCircleConfig$inboundSchema,
  BankingCircleConfig$Outbound,
  BankingCircleConfig$outboundSchema,
} from "./bankingcircleconfig.js";
import {
  CurrencyCloudConfig,
  CurrencyCloudConfig$inboundSchema,
  CurrencyCloudConfig$Outbound,
  CurrencyCloudConfig$outboundSchema,
} from "./currencycloudconfig.js";
import {
  DummyPayConfig,
  DummyPayConfig$inboundSchema,
  DummyPayConfig$Outbound,
  DummyPayConfig$outboundSchema,
} from "./dummypayconfig.js";
import {
  GenericConfig,
  GenericConfig$inboundSchema,
  GenericConfig$Outbound,
  GenericConfig$outboundSchema,
} from "./genericconfig.js";
import {
  MangoPayConfig,
  MangoPayConfig$inboundSchema,
  MangoPayConfig$Outbound,
  MangoPayConfig$outboundSchema,
} from "./mangopayconfig.js";
import {
  ModulrConfig,
  ModulrConfig$inboundSchema,
  ModulrConfig$Outbound,
  ModulrConfig$outboundSchema,
} from "./modulrconfig.js";
import {
  MoneycorpConfig,
  MoneycorpConfig$inboundSchema,
  MoneycorpConfig$Outbound,
  MoneycorpConfig$outboundSchema,
} from "./moneycorpconfig.js";
import {
  StripeConfig,
  StripeConfig$inboundSchema,
  StripeConfig$Outbound,
  StripeConfig$outboundSchema,
} from "./stripeconfig.js";
import {
  WiseConfig,
  WiseConfig$inboundSchema,
  WiseConfig$Outbound,
  WiseConfig$outboundSchema,
} from "./wiseconfig.js";

export type ConnectorConfig =
  | WiseConfig
  | StripeConfig
  | GenericConfig
  | ModulrConfig
  | CurrencyCloudConfig
  | MangoPayConfig
  | MoneycorpConfig
  | AdyenConfig
  | DummyPayConfig
  | AtlarConfig
  | BankingCircleConfig;

/** @internal */
export const ConnectorConfig$inboundSchema: z.ZodType<
  ConnectorConfig,
  z.ZodTypeDef,
  unknown
> = z.union([
  WiseConfig$inboundSchema,
  StripeConfig$inboundSchema,
  GenericConfig$inboundSchema,
  ModulrConfig$inboundSchema,
  CurrencyCloudConfig$inboundSchema,
  MangoPayConfig$inboundSchema,
  MoneycorpConfig$inboundSchema,
  AdyenConfig$inboundSchema,
  DummyPayConfig$inboundSchema,
  AtlarConfig$inboundSchema,
  BankingCircleConfig$inboundSchema,
]);

/** @internal */
export type ConnectorConfig$Outbound =
  | WiseConfig$Outbound
  | StripeConfig$Outbound
  | GenericConfig$Outbound
  | ModulrConfig$Outbound
  | CurrencyCloudConfig$Outbound
  | MangoPayConfig$Outbound
  | MoneycorpConfig$Outbound
  | AdyenConfig$Outbound
  | DummyPayConfig$Outbound
  | AtlarConfig$Outbound
  | BankingCircleConfig$Outbound;

/** @internal */
export const ConnectorConfig$outboundSchema: z.ZodType<
  ConnectorConfig$Outbound,
  z.ZodTypeDef,
  ConnectorConfig
> = z.union([
  WiseConfig$outboundSchema,
  StripeConfig$outboundSchema,
  GenericConfig$outboundSchema,
  ModulrConfig$outboundSchema,
  CurrencyCloudConfig$outboundSchema,
  MangoPayConfig$outboundSchema,
  MoneycorpConfig$outboundSchema,
  AdyenConfig$outboundSchema,
  DummyPayConfig$outboundSchema,
  AtlarConfig$outboundSchema,
  BankingCircleConfig$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ConnectorConfig$ {
  /** @deprecated use `ConnectorConfig$inboundSchema` instead. */
  export const inboundSchema = ConnectorConfig$inboundSchema;
  /** @deprecated use `ConnectorConfig$outboundSchema` instead. */
  export const outboundSchema = ConnectorConfig$outboundSchema;
  /** @deprecated use `ConnectorConfig$Outbound` instead. */
  export type Outbound = ConnectorConfig$Outbound;
}
