/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateWorkflowRequest = {
  name?: string | undefined;
  stages: Array<{ [k: string]: any }>;
};

/** @internal */
export const CreateWorkflowRequest$inboundSchema: z.ZodType<
  CreateWorkflowRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  stages: z.array(z.record(z.any())),
});
/** @internal */
export type CreateWorkflowRequest$Outbound = {
  name?: string | undefined;
  stages: Array<{ [k: string]: any }>;
};

/** @internal */
export const CreateWorkflowRequest$outboundSchema: z.ZodType<
  CreateWorkflowRequest$Outbound,
  z.ZodTypeDef,
  CreateWorkflowRequest
> = z.object({
  name: z.string().optional(),
  stages: z.array(z.record(z.any())),
});

export function createWorkflowRequestToJSON(
  createWorkflowRequest: CreateWorkflowRequest,
): string {
  return JSON.stringify(
    CreateWorkflowRequest$outboundSchema.parse(createWorkflowRequest),
  );
}
export function createWorkflowRequestFromJSON(
  jsonString: string,
): SafeParseResult<CreateWorkflowRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateWorkflowRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateWorkflowRequest' from JSON`,
  );
}
