/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { Hold, Hold$ } from "./hold";
import * as z from "zod";

export type DebitWalletResponse = {
    data: Hold;
};

/** @internal */
export namespace DebitWalletResponse$ {
    export type Inbound = {
        data: Hold$.Inbound;
    };

    export const inboundSchema: z.ZodType<DebitWalletResponse, z.ZodTypeDef, Inbound> = z
        .object({
            data: Hold$.inboundSchema,
        })
        .transform((v) => {
            return {
                data: v.data,
            };
        });

    export type Outbound = {
        data: Hold$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DebitWalletResponse> = z
        .object({
            data: Hold$.outboundSchema,
        })
        .transform((v) => {
            return {
                data: v.data,
            };
        });
}
