/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  WalletSummary,
  WalletSummary$inboundSchema,
  WalletSummary$Outbound,
  WalletSummary$outboundSchema,
} from "./walletsummary.js";

export type GetWalletSummaryResponse = {
  data: WalletSummary;
};

/** @internal */
export const GetWalletSummaryResponse$inboundSchema: z.ZodType<
  GetWalletSummaryResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: WalletSummary$inboundSchema,
});

/** @internal */
export type GetWalletSummaryResponse$Outbound = {
  data: WalletSummary$Outbound;
};

/** @internal */
export const GetWalletSummaryResponse$outboundSchema: z.ZodType<
  GetWalletSummaryResponse$Outbound,
  z.ZodTypeDef,
  GetWalletSummaryResponse
> = z.object({
  data: WalletSummary$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetWalletSummaryResponse$ {
  /** @deprecated use `GetWalletSummaryResponse$inboundSchema` instead. */
  export const inboundSchema = GetWalletSummaryResponse$inboundSchema;
  /** @deprecated use `GetWalletSummaryResponse$outboundSchema` instead. */
  export const outboundSchema = GetWalletSummaryResponse$outboundSchema;
  /** @deprecated use `GetWalletSummaryResponse$Outbound` instead. */
  export type Outbound = GetWalletSummaryResponse$Outbound;
}

export function getWalletSummaryResponseToJSON(
  getWalletSummaryResponse: GetWalletSummaryResponse,
): string {
  return JSON.stringify(
    GetWalletSummaryResponse$outboundSchema.parse(getWalletSummaryResponse),
  );
}

export function getWalletSummaryResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetWalletSummaryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWalletSummaryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWalletSummaryResponse' from JSON`,
  );
}
