/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Trigger, Trigger$inboundSchema } from "./trigger.js";

export type ListTriggersResponse = {
  data: Array<Trigger>;
};

/** @internal */
export const ListTriggersResponse$inboundSchema: z.ZodType<
  ListTriggersResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(Trigger$inboundSchema),
});

export function listTriggersResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListTriggersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListTriggersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListTriggersResponse' from JSON`,
  );
}
