/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types";
import * as z from "zod";

export const Type = {
    NewTransaction: "NEW_TRANSACTION",
    SetMetadata: "SET_METADATA",
} as const;
export type Type = ClosedEnum<typeof Type>;

export type Log = {
    data: Record<string, any>;
    date: Date;
    hash: string;
    id: number;
    type: Type;
};

/** @internal */
export namespace Type$ {
    export const inboundSchema = z.nativeEnum(Type);
    export const outboundSchema = inboundSchema;
}

/** @internal */
export namespace Log$ {
    export const inboundSchema: z.ZodType<Log, z.ZodTypeDef, unknown> = z
        .object({
            data: z.record(z.any()),
            date: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v)),
            hash: z.string(),
            id: z.number().int(),
            type: Type$.inboundSchema,
        })
        .transform((v) => {
            return {
                data: v.data,
                date: v.date,
                hash: v.hash,
                id: v.id,
                type: v.type,
            };
        });

    export type Outbound = {
        data: Record<string, any>;
        date: string;
        hash: string;
        id: number;
        type: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Log> = z
        .object({
            data: z.record(z.any()),
            date: z.date().transform((v) => v.toISOString()),
            hash: z.string(),
            id: z.number().int(),
            type: Type$.outboundSchema,
        })
        .transform((v) => {
            return {
                data: v.data,
                date: v.date,
                hash: v.hash,
                id: v.id,
                type: v.type,
            };
        });
}
