/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export enum OrchestrationPaymentStatus {
    Pending = "PENDING",
    Active = "ACTIVE",
    Terminated = "TERMINATED",
    Failed = "FAILED",
    Succeeded = "SUCCEEDED",
    Cancelled = "CANCELLED",
}

/** @internal */
export const OrchestrationPaymentStatus$ = z.nativeEnum(OrchestrationPaymentStatus);
