/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    Payment,
    Payment$inboundSchema,
    Payment$Outbound,
    Payment$outboundSchema,
} from "./payment.js";
import * as z from "zod";

export type PaymentsCursorCursor = {
    data: Array<Payment>;
    hasMore: boolean;
    next?: string | undefined;
    pageSize: number;
    previous?: string | undefined;
};

export type PaymentsCursor = {
    cursor: PaymentsCursorCursor;
};

/** @internal */
export const PaymentsCursorCursor$inboundSchema: z.ZodType<
    PaymentsCursorCursor,
    z.ZodTypeDef,
    unknown
> = z.object({
    data: z.array(Payment$inboundSchema),
    hasMore: z.boolean(),
    next: z.string().optional(),
    pageSize: z.number().int(),
    previous: z.string().optional(),
});

/** @internal */
export type PaymentsCursorCursor$Outbound = {
    data: Array<Payment$Outbound>;
    hasMore: boolean;
    next?: string | undefined;
    pageSize: number;
    previous?: string | undefined;
};

/** @internal */
export const PaymentsCursorCursor$outboundSchema: z.ZodType<
    PaymentsCursorCursor$Outbound,
    z.ZodTypeDef,
    PaymentsCursorCursor
> = z.object({
    data: z.array(Payment$outboundSchema),
    hasMore: z.boolean(),
    next: z.string().optional(),
    pageSize: z.number().int(),
    previous: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentsCursorCursor$ {
    /** @deprecated use `PaymentsCursorCursor$inboundSchema` instead. */
    export const inboundSchema = PaymentsCursorCursor$inboundSchema;
    /** @deprecated use `PaymentsCursorCursor$outboundSchema` instead. */
    export const outboundSchema = PaymentsCursorCursor$outboundSchema;
    /** @deprecated use `PaymentsCursorCursor$Outbound` instead. */
    export type Outbound = PaymentsCursorCursor$Outbound;
}

/** @internal */
export const PaymentsCursor$inboundSchema: z.ZodType<PaymentsCursor, z.ZodTypeDef, unknown> =
    z.object({
        cursor: z.lazy(() => PaymentsCursorCursor$inboundSchema),
    });

/** @internal */
export type PaymentsCursor$Outbound = {
    cursor: PaymentsCursorCursor$Outbound;
};

/** @internal */
export const PaymentsCursor$outboundSchema: z.ZodType<
    PaymentsCursor$Outbound,
    z.ZodTypeDef,
    PaymentsCursor
> = z.object({
    cursor: z.lazy(() => PaymentsCursorCursor$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PaymentsCursor$ {
    /** @deprecated use `PaymentsCursor$inboundSchema` instead. */
    export const inboundSchema = PaymentsCursor$inboundSchema;
    /** @deprecated use `PaymentsCursor$outboundSchema` instead. */
    export const outboundSchema = PaymentsCursor$outboundSchema;
    /** @deprecated use `PaymentsCursor$Outbound` instead. */
    export type Outbound = PaymentsCursor$Outbound;
}
