/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types";
import * as z from "zod";

export const PaymentType = {
    PayIn: "PAY-IN",
    Payout: "PAYOUT",
    Transfer: "TRANSFER",
    Other: "OTHER",
} as const;
export type PaymentType = ClosedEnum<typeof PaymentType>;

/** @internal */
export namespace PaymentType$ {
    export const inboundSchema = z.nativeEnum(PaymentType);
    export const outboundSchema = inboundSchema;
}
