/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type Posting = {
    amount: bigint;
    asset: string;
    destination: string;
    source: string;
};

/** @internal */
export namespace Posting$ {
    export type Inbound = {
        amount: number;
        asset: string;
        destination: string;
        source: string;
    };

    export const inboundSchema: z.ZodType<Posting, z.ZodTypeDef, Inbound> = z
        .object({
            amount: z.number().transform((v) => BigInt(v)),
            asset: z.string(),
            destination: z.string(),
            source: z.string(),
        })
        .transform((v) => {
            return {
                amount: v.amount,
                asset: v.asset,
                destination: v.destination,
                source: v.source,
            };
        });

    export type Outbound = {
        amount: number;
        asset: string;
        destination: string;
        source: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Posting> = z
        .object({
            amount: z.bigint().transform((v) => Number(v)),
            asset: z.string(),
            destination: z.string(),
            source: z.string(),
        })
        .transform((v) => {
            return {
                amount: v.amount,
                asset: v.asset,
                destination: v.destination,
                source: v.source,
            };
        });
}
