/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Client, Client$inboundSchema } from "./client.js";

export type ReadClientResponse = {
  data?: Client | undefined;
};

/** @internal */
export const ReadClientResponse$inboundSchema: z.ZodType<
  ReadClientResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: Client$inboundSchema.optional(),
});

export function readClientResponseFromJSON(
  jsonString: string,
): SafeParseResult<ReadClientResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReadClientResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReadClientResponse' from JSON`,
  );
}
