/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { ErrorsEnum, ErrorsEnum$inboundSchema } from "./errorsenum.js";
import { Transaction, Transaction$inboundSchema } from "./transaction.js";

export type ScriptResponse = {
  details?: string | undefined;
  errorCode?: ErrorsEnum | undefined;
  errorMessage?: string | undefined;
  transaction?: Transaction | undefined;
};

/** @internal */
export const ScriptResponse$inboundSchema: z.ZodType<
  ScriptResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  details: z.string().optional(),
  errorCode: ErrorsEnum$inboundSchema.optional(),
  errorMessage: z.string().optional(),
  transaction: Transaction$inboundSchema.optional(),
});

export function scriptResponseFromJSON(
  jsonString: string,
): SafeParseResult<ScriptResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ScriptResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ScriptResponse' from JSON`,
  );
}
