/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
    TransferInitiation,
    TransferInitiation$inboundSchema,
    TransferInitiation$Outbound,
    TransferInitiation$outboundSchema,
} from "./transferinitiation.js";
import * as z from "zod";

export type TransferInitiationResponse = {
    data: TransferInitiation;
};

/** @internal */
export const TransferInitiationResponse$inboundSchema: z.ZodType<
    TransferInitiationResponse,
    z.ZodTypeDef,
    unknown
> = z.object({
    data: TransferInitiation$inboundSchema,
});

/** @internal */
export type TransferInitiationResponse$Outbound = {
    data: TransferInitiation$Outbound;
};

/** @internal */
export const TransferInitiationResponse$outboundSchema: z.ZodType<
    TransferInitiationResponse$Outbound,
    z.ZodTypeDef,
    TransferInitiationResponse
> = z.object({
    data: TransferInitiation$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace TransferInitiationResponse$ {
    /** @deprecated use `TransferInitiationResponse$inboundSchema` instead. */
    export const inboundSchema = TransferInitiationResponse$inboundSchema;
    /** @deprecated use `TransferInitiationResponse$outboundSchema` instead. */
    export const outboundSchema = TransferInitiationResponse$outboundSchema;
    /** @deprecated use `TransferInitiationResponse$Outbound` instead. */
    export type Outbound = TransferInitiationResponse$Outbound;
}
