/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateBankAccountMetadataRequest = {
  metadata: { [k: string]: string } | null;
};

/** @internal */
export const UpdateBankAccountMetadataRequest$inboundSchema: z.ZodType<
  UpdateBankAccountMetadataRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  metadata: z.nullable(z.record(z.string())),
});

/** @internal */
export type UpdateBankAccountMetadataRequest$Outbound = {
  metadata: { [k: string]: string } | null;
};

/** @internal */
export const UpdateBankAccountMetadataRequest$outboundSchema: z.ZodType<
  UpdateBankAccountMetadataRequest$Outbound,
  z.ZodTypeDef,
  UpdateBankAccountMetadataRequest
> = z.object({
  metadata: z.nullable(z.record(z.string())),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateBankAccountMetadataRequest$ {
  /** @deprecated use `UpdateBankAccountMetadataRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateBankAccountMetadataRequest$inboundSchema;
  /** @deprecated use `UpdateBankAccountMetadataRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateBankAccountMetadataRequest$outboundSchema;
  /** @deprecated use `UpdateBankAccountMetadataRequest$Outbound` instead. */
  export type Outbound = UpdateBankAccountMetadataRequest$Outbound;
}

export function updateBankAccountMetadataRequestToJSON(
  updateBankAccountMetadataRequest: UpdateBankAccountMetadataRequest,
): string {
  return JSON.stringify(
    UpdateBankAccountMetadataRequest$outboundSchema.parse(
      updateBankAccountMetadataRequest,
    ),
  );
}

export function updateBankAccountMetadataRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateBankAccountMetadataRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateBankAccountMetadataRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateBankAccountMetadataRequest' from JSON`,
  );
}
