/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { V2Account, V2Account$ } from "./v2account";
import { z } from "zod";

export type V2AccountResponse = {
    data: V2Account;
};

/** @internal */
export namespace V2AccountResponse$ {
    export type Inbound = {
        data: V2Account$.Inbound;
    };

    export const inboundSchema: z.ZodType<V2AccountResponse, z.ZodTypeDef, Inbound> = z
        .object({
            data: V2Account$.inboundSchema,
        })
        .transform((v) => {
            return {
                data: v.data,
            };
        });

    export type Outbound = {
        data: V2Account$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, V2AccountResponse> = z
        .object({
            data: V2Account$.outboundSchema,
        })
        .transform((v) => {
            return {
                data: v.data,
            };
        });
}
