/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V2AssetHolder = {
  assets: { [k: string]: bigint };
};

/** @internal */
export const V2AssetHolder$inboundSchema: z.ZodType<
  V2AssetHolder,
  z.ZodTypeDef,
  unknown
> = z.object({
  assets: z.record(z.number().transform(v => BigInt(v))),
});

export function v2AssetHolderFromJSON(
  jsonString: string,
): SafeParseResult<V2AssetHolder, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V2AssetHolder$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V2AssetHolder' from JSON`,
  );
}
