/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export enum V2Connector {
  Stripe = "STRIPE",
  DummyPay = "DUMMY-PAY",
  Wise = "WISE",
  Modulr = "MODULR",
  CurrencyCloud = "CURRENCY-CLOUD",
  BankingCircle = "BANKING-CIRCLE",
  Mangopay = "MANGOPAY",
  Moneycorp = "MONEYCORP",
}

/** @internal */
export const V2Connector$inboundSchema: z.ZodNativeEnum<typeof V2Connector> = z
  .nativeEnum(V2Connector);
