/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { V2LedgerInfo } from "./v2ledgerinfo";
import { Expose, Type } from "class-transformer";

export class V2LedgerInfoResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => V2LedgerInfo)
    data?: V2LedgerInfo;
}
