/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V2Ledger = {
  addedAt: Date;
  bucket: string;
  deletedAt?: Date | null | undefined;
  features?: { [k: string]: string } | undefined;
  id?: number | undefined;
  metadata?: { [k: string]: string } | undefined;
  name: string;
};

/** @internal */
export const V2Ledger$inboundSchema: z.ZodType<
  V2Ledger,
  z.ZodTypeDef,
  unknown
> = z.object({
  addedAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  bucket: z.string(),
  deletedAt: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  features: z.record(z.string()).optional(),
  id: z.number().int().optional(),
  metadata: z.record(z.string()).optional(),
  name: z.string(),
});

export function v2LedgerFromJSON(
  jsonString: string,
): SafeParseResult<V2Ledger, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V2Ledger$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V2Ledger' from JSON`,
  );
}
