/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  V2WorkflowInstance,
  V2WorkflowInstance$inboundSchema,
} from "./v2workflowinstance.js";

export type V2ListRunsResponseCursor = {
  data: Array<V2WorkflowInstance>;
  hasMore: boolean;
  next?: string | undefined;
  pageSize: number;
  previous?: string | undefined;
};

export type V2ListRunsResponse = {
  cursor: V2ListRunsResponseCursor;
};

/** @internal */
export const V2ListRunsResponseCursor$inboundSchema: z.ZodType<
  V2ListRunsResponseCursor,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(V2WorkflowInstance$inboundSchema),
  hasMore: z.boolean(),
  next: z.string().optional(),
  pageSize: z.number().int(),
  previous: z.string().optional(),
});

export function v2ListRunsResponseCursorFromJSON(
  jsonString: string,
): SafeParseResult<V2ListRunsResponseCursor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V2ListRunsResponseCursor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V2ListRunsResponseCursor' from JSON`,
  );
}

/** @internal */
export const V2ListRunsResponse$inboundSchema: z.ZodType<
  V2ListRunsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  cursor: z.lazy(() => V2ListRunsResponseCursor$inboundSchema),
});

export function v2ListRunsResponseFromJSON(
  jsonString: string,
): SafeParseResult<V2ListRunsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V2ListRunsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V2ListRunsResponse' from JSON`,
  );
}
