/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import {
    V2StageDelay,
    V2StageDelay$inboundSchema,
    V2StageDelay$Outbound,
    V2StageDelay$outboundSchema,
} from "./v2stagedelay.js";
import {
    V2StageSend,
    V2StageSend$inboundSchema,
    V2StageSend$Outbound,
    V2StageSend$outboundSchema,
} from "./v2stagesend.js";
import {
    V2StageWaitEvent,
    V2StageWaitEvent$inboundSchema,
    V2StageWaitEvent$Outbound,
    V2StageWaitEvent$outboundSchema,
} from "./v2stagewaitevent.js";
import {
    V2Update,
    V2Update$inboundSchema,
    V2Update$Outbound,
    V2Update$outboundSchema,
} from "./v2update.js";
import * as z from "zod";

export type V2Stage = V2StageWaitEvent | V2Update | V2StageDelay | V2StageSend;

/** @internal */
export const V2Stage$inboundSchema: z.ZodType<V2Stage, z.ZodTypeDef, unknown> = z.union([
    V2StageWaitEvent$inboundSchema,
    V2Update$inboundSchema,
    V2StageDelay$inboundSchema,
    V2StageSend$inboundSchema,
]);

/** @internal */
export type V2Stage$Outbound =
    | V2StageWaitEvent$Outbound
    | V2Update$Outbound
    | V2StageDelay$Outbound
    | V2StageSend$Outbound;

/** @internal */
export const V2Stage$outboundSchema: z.ZodType<V2Stage$Outbound, z.ZodTypeDef, V2Stage> = z.union([
    V2StageWaitEvent$outboundSchema,
    V2Update$outboundSchema,
    V2StageDelay$outboundSchema,
    V2StageSend$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V2Stage$ {
    /** @deprecated use `V2Stage$inboundSchema` instead. */
    export const inboundSchema = V2Stage$inboundSchema;
    /** @deprecated use `V2Stage$outboundSchema` instead. */
    export const outboundSchema = V2Stage$outboundSchema;
    /** @deprecated use `V2Stage$Outbound` instead. */
    export type Outbound = V2Stage$Outbound;
}
