/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { V2StageSendSourceAccount, V2StageSendSourceAccount$ } from "./v2stagesendsourceaccount";
import { V2StageSendSourcePayment, V2StageSendSourcePayment$ } from "./v2stagesendsourcepayment";
import { V2StageSendSourceWallet, V2StageSendSourceWallet$ } from "./v2stagesendsourcewallet";
import * as z from "zod";

export type V2StageSendSource = {
    account?: V2StageSendSourceAccount | undefined;
    payment?: V2StageSendSourcePayment | undefined;
    wallet?: V2StageSendSourceWallet | undefined;
};

/** @internal */
export namespace V2StageSendSource$ {
    export const inboundSchema: z.ZodType<V2StageSendSource, z.ZodTypeDef, unknown> = z
        .object({
            account: V2StageSendSourceAccount$.inboundSchema.optional(),
            payment: V2StageSendSourcePayment$.inboundSchema.optional(),
            wallet: V2StageSendSourceWallet$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.account === undefined ? null : { account: v.account }),
                ...(v.payment === undefined ? null : { payment: v.payment }),
                ...(v.wallet === undefined ? null : { wallet: v.wallet }),
            };
        });

    export type Outbound = {
        account?: V2StageSendSourceAccount$.Outbound | undefined;
        payment?: V2StageSendSourcePayment$.Outbound | undefined;
        wallet?: V2StageSendSourceWallet$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, V2StageSendSource> = z
        .object({
            account: V2StageSendSourceAccount$.outboundSchema.optional(),
            payment: V2StageSendSourcePayment$.outboundSchema.optional(),
            wallet: V2StageSendSourceWallet$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.account === undefined ? null : { account: v.account }),
                ...(v.payment === undefined ? null : { payment: v.payment }),
                ...(v.wallet === undefined ? null : { wallet: v.wallet }),
            };
        });
}
