/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export enum V2TargetType {
    Transaction = "TRANSACTION",
    Account = "ACCOUNT",
}

/** @internal */
export const V2TargetType$ = z.nativeEnum(V2TargetType);
