/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { V3Task, V3Task$inboundSchema } from "./v3task.js";

export type V3GetTaskResponse = {
  data: V3Task;
};

/** @internal */
export const V3GetTaskResponse$inboundSchema: z.ZodType<
  V3GetTaskResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: V3Task$inboundSchema,
});

export function v3GetTaskResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3GetTaskResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3GetTaskResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3GetTaskResponse' from JSON`,
  );
}
