/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { V3Pool, V3Pool$inboundSchema } from "./v3pool.js";

export type V3GetPoolResponse = {
  data: V3Pool;
};

/** @internal */
export const V3GetPoolResponse$inboundSchema: z.ZodType<
  V3GetPoolResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: V3Pool$inboundSchema,
});

export function v3GetPoolResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3GetPoolResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3GetPoolResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3GetPoolResponse' from JSON`,
  );
}
