/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V3PaymentServiceUserDeleteConnectorResponseData = {
  /**
   * Since this call is asynchronous, the response will contain the ID of the task that was created to delete the payment service user on the connector. You can use the task API to check the status of the task.
   *
   * @remarks
   */
  taskID: string;
};

export type V3PaymentServiceUserDeleteConnectorResponse = {
  data: V3PaymentServiceUserDeleteConnectorResponseData;
};

/** @internal */
export const V3PaymentServiceUserDeleteConnectorResponseData$inboundSchema:
  z.ZodType<
    V3PaymentServiceUserDeleteConnectorResponseData,
    z.ZodTypeDef,
    unknown
  > = z.object({
    taskID: z.string(),
  });

export function v3PaymentServiceUserDeleteConnectorResponseDataFromJSON(
  jsonString: string,
): SafeParseResult<
  V3PaymentServiceUserDeleteConnectorResponseData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3PaymentServiceUserDeleteConnectorResponseData$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V3PaymentServiceUserDeleteConnectorResponseData' from JSON`,
  );
}

/** @internal */
export const V3PaymentServiceUserDeleteConnectorResponse$inboundSchema:
  z.ZodType<
    V3PaymentServiceUserDeleteConnectorResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: z.lazy(() =>
      V3PaymentServiceUserDeleteConnectorResponseData$inboundSchema
    ),
  });

export function v3PaymentServiceUserDeleteConnectorResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  V3PaymentServiceUserDeleteConnectorResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3PaymentServiceUserDeleteConnectorResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V3PaymentServiceUserDeleteConnectorResponse' from JSON`,
  );
}
