/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  V3PaymentServiceUserLinkAttempt,
  V3PaymentServiceUserLinkAttempt$inboundSchema,
} from "./v3paymentserviceuserlinkattempt.js";

export type V3PaymentServiceUserLinkAttemptsCursorResponseCursor = {
  data: Array<V3PaymentServiceUserLinkAttempt>;
  hasMore: boolean;
  next?: string | undefined;
  pageSize: number;
  previous?: string | undefined;
};

export type V3PaymentServiceUserLinkAttemptsCursorResponse = {
  cursor: V3PaymentServiceUserLinkAttemptsCursorResponseCursor;
};

/** @internal */
export const V3PaymentServiceUserLinkAttemptsCursorResponseCursor$inboundSchema:
  z.ZodType<
    V3PaymentServiceUserLinkAttemptsCursorResponseCursor,
    z.ZodTypeDef,
    unknown
  > = z.object({
    data: z.array(V3PaymentServiceUserLinkAttempt$inboundSchema),
    hasMore: z.boolean(),
    next: z.string().optional(),
    pageSize: z.number().int(),
    previous: z.string().optional(),
  });

export function v3PaymentServiceUserLinkAttemptsCursorResponseCursorFromJSON(
  jsonString: string,
): SafeParseResult<
  V3PaymentServiceUserLinkAttemptsCursorResponseCursor,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3PaymentServiceUserLinkAttemptsCursorResponseCursor$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V3PaymentServiceUserLinkAttemptsCursorResponseCursor' from JSON`,
  );
}

/** @internal */
export const V3PaymentServiceUserLinkAttemptsCursorResponse$inboundSchema:
  z.ZodType<
    V3PaymentServiceUserLinkAttemptsCursorResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    cursor: z.lazy(() =>
      V3PaymentServiceUserLinkAttemptsCursorResponseCursor$inboundSchema
    ),
  });

export function v3PaymentServiceUserLinkAttemptsCursorResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  V3PaymentServiceUserLinkAttemptsCursorResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3PaymentServiceUserLinkAttemptsCursorResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V3PaymentServiceUserLinkAttemptsCursorResponse' from JSON`,
  );
}
