/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type WalletSubject = {
    balance?: string | undefined;
    identifier: string;
    type: string;
};

/** @internal */
export const WalletSubject$inboundSchema: z.ZodType<WalletSubject, z.ZodTypeDef, unknown> =
    z.object({
        balance: z.string().optional(),
        identifier: z.string(),
        type: z.string(),
    });

/** @internal */
export type WalletSubject$Outbound = {
    balance?: string | undefined;
    identifier: string;
    type: string;
};

/** @internal */
export const WalletSubject$outboundSchema: z.ZodType<
    WalletSubject$Outbound,
    z.ZodTypeDef,
    WalletSubject
> = z.object({
    balance: z.string().optional(),
    identifier: z.string(),
    type: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WalletSubject$ {
    /** @deprecated use `WalletSubject$inboundSchema` instead. */
    export const inboundSchema = WalletSubject$inboundSchema;
    /** @deprecated use `WalletSubject$outboundSchema` instead. */
    export const outboundSchema = WalletSubject$outboundSchema;
    /** @deprecated use `WalletSubject$Outbound` instead. */
    export type Outbound = WalletSubject$Outbound;
}
