/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { StageStatus, StageStatus$ } from "./stagestatus";
import * as z from "zod";

export type WorkflowInstance = {
    createdAt: Date;
    error?: string | undefined;
    id: string;
    status?: Array<StageStatus> | undefined;
    terminated: boolean;
    terminatedAt?: Date | undefined;
    updatedAt: Date;
    workflowID: string;
};

/** @internal */
export namespace WorkflowInstance$ {
    export type Inbound = {
        createdAt: string;
        error?: string | undefined;
        id: string;
        status?: Array<StageStatus$.Inbound> | undefined;
        terminated: boolean;
        terminatedAt?: string | undefined;
        updatedAt: string;
        workflowID: string;
    };

    export const inboundSchema: z.ZodType<WorkflowInstance, z.ZodTypeDef, Inbound> = z
        .object({
            createdAt: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v)),
            error: z.string().optional(),
            id: z.string(),
            status: z.array(StageStatus$.inboundSchema).optional(),
            terminated: z.boolean(),
            terminatedAt: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v))
                .optional(),
            updatedAt: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v)),
            workflowID: z.string(),
        })
        .transform((v) => {
            return {
                createdAt: v.createdAt,
                ...(v.error === undefined ? null : { error: v.error }),
                id: v.id,
                ...(v.status === undefined ? null : { status: v.status }),
                terminated: v.terminated,
                ...(v.terminatedAt === undefined ? null : { terminatedAt: v.terminatedAt }),
                updatedAt: v.updatedAt,
                workflowID: v.workflowID,
            };
        });

    export type Outbound = {
        createdAt: string;
        error?: string | undefined;
        id: string;
        status?: Array<StageStatus$.Outbound> | undefined;
        terminated: boolean;
        terminatedAt?: string | undefined;
        updatedAt: string;
        workflowID: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, WorkflowInstance> = z
        .object({
            createdAt: z.date().transform((v) => v.toISOString()),
            error: z.string().optional(),
            id: z.string(),
            status: z.array(StageStatus$.outboundSchema).optional(),
            terminated: z.boolean(),
            terminatedAt: z
                .date()
                .transform((v) => v.toISOString())
                .optional(),
            updatedAt: z.date().transform((v) => v.toISOString()),
            workflowID: z.string(),
        })
        .transform((v) => {
            return {
                createdAt: v.createdAt,
                ...(v.error === undefined ? null : { error: v.error }),
                id: v.id,
                ...(v.status === undefined ? null : { status: v.status }),
                terminated: v.terminated,
                ...(v.terminatedAt === undefined ? null : { terminatedAt: v.terminatedAt }),
                updatedAt: v.updatedAt,
                workflowID: v.workflowID,
            };
        });
}
