/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyMetadata } from "../../../internal/utils";
import { classToPlain, Expose } from "class-transformer";

export enum V2ErrorErrorCode {
    Validation = "VALIDATION",
    NotFound = "NOT_FOUND",
    Internal = "INTERNAL",
}

export class V2Error extends Error {
    @SpeakeasyMetadata()
    @Expose({ name: "errorCode" })
    errorCode: V2ErrorErrorCode;

    @SpeakeasyMetadata()
    @Expose({ name: "errorMessage" })
    errorMessage: string;

    constructor(err?: V2Error) {
        super();
        if (err) {
            Object.assign(this, err);
            this.message = JSON.stringify(
                classToPlain(err, { exposeUnsetFields: false, excludeExtraneousValues: true })
            );
        }

        this.name = "V2Error";
        Object.setPrototypeOf(this, V2Error.prototype);
    }
}
