/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as wallets from "../wallets/index.js";

export const CreditWalletServerList = [
  "http://localhost:8080/",
] as const;

export type CreditWalletRequest = {
  creditWalletRequest?: wallets.CreditWalletRequest | undefined;
  /**
   * Use an idempotency key
   */
  idempotencyKey?: string | undefined;
  id: string;
};

export type CreditWalletResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
};

/** @internal */
export type CreditWalletRequest$Outbound = {
  CreditWalletRequest?: wallets.CreditWalletRequest$Outbound | undefined;
  "Idempotency-Key"?: string | undefined;
  id: string;
};

/** @internal */
export const CreditWalletRequest$outboundSchema: z.ZodType<
  CreditWalletRequest$Outbound,
  z.ZodTypeDef,
  CreditWalletRequest
> = z.object({
  creditWalletRequest: wallets.CreditWalletRequest$outboundSchema.optional(),
  idempotencyKey: z.string().optional(),
  id: z.string(),
}).transform((v) => {
  return remap$(v, {
    creditWalletRequest: "CreditWalletRequest",
    idempotencyKey: "Idempotency-Key",
  });
});

export function creditWalletRequestToJSON(
  creditWalletRequest: CreditWalletRequest,
): string {
  return JSON.stringify(
    CreditWalletRequest$outboundSchema.parse(creditWalletRequest),
  );
}

/** @internal */
export const CreditWalletResponse$inboundSchema: z.ZodType<
  CreditWalletResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

export function creditWalletResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreditWalletResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreditWalletResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreditWalletResponse' from JSON`,
  );
}
