/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteConfigRequest = {
  /**
   * Config ID
   */
  id: string;
};

export type DeleteConfigResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
};

/** @internal */
export type DeleteConfigRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteConfigRequest$outboundSchema: z.ZodType<
  DeleteConfigRequest$Outbound,
  z.ZodTypeDef,
  DeleteConfigRequest
> = z.object({
  id: z.string(),
});

export function deleteConfigRequestToJSON(
  deleteConfigRequest: DeleteConfigRequest,
): string {
  return JSON.stringify(
    DeleteConfigRequest$outboundSchema.parse(deleteConfigRequest),
  );
}

/** @internal */
export const DeleteConfigResponse$inboundSchema: z.ZodType<
  DeleteConfigResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

export function deleteConfigResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteConfigResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteConfigResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteConfigResponse' from JSON`,
  );
}
