/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type GetWalletSummaryRequest = {
  id: string;
};

export type GetWalletSummaryResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * Wallet summary
   */
  getWalletSummaryResponse?: shared.GetWalletSummaryResponse | undefined;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
};

/** @internal */
export const GetWalletSummaryRequest$inboundSchema: z.ZodType<
  GetWalletSummaryRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type GetWalletSummaryRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetWalletSummaryRequest$outboundSchema: z.ZodType<
  GetWalletSummaryRequest$Outbound,
  z.ZodTypeDef,
  GetWalletSummaryRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetWalletSummaryRequest$ {
  /** @deprecated use `GetWalletSummaryRequest$inboundSchema` instead. */
  export const inboundSchema = GetWalletSummaryRequest$inboundSchema;
  /** @deprecated use `GetWalletSummaryRequest$outboundSchema` instead. */
  export const outboundSchema = GetWalletSummaryRequest$outboundSchema;
  /** @deprecated use `GetWalletSummaryRequest$Outbound` instead. */
  export type Outbound = GetWalletSummaryRequest$Outbound;
}

export function getWalletSummaryRequestToJSON(
  getWalletSummaryRequest: GetWalletSummaryRequest,
): string {
  return JSON.stringify(
    GetWalletSummaryRequest$outboundSchema.parse(getWalletSummaryRequest),
  );
}

export function getWalletSummaryRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetWalletSummaryRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWalletSummaryRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWalletSummaryRequest' from JSON`,
  );
}

/** @internal */
export const GetWalletSummaryResponse$inboundSchema: z.ZodType<
  GetWalletSummaryResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  GetWalletSummaryResponse: shared.GetWalletSummaryResponse$inboundSchema
    .optional(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "GetWalletSummaryResponse": "getWalletSummaryResponse",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

/** @internal */
export type GetWalletSummaryResponse$Outbound = {
  ContentType: string;
  GetWalletSummaryResponse?:
    | shared.GetWalletSummaryResponse$Outbound
    | undefined;
  StatusCode: number;
  RawResponse: never;
};

/** @internal */
export const GetWalletSummaryResponse$outboundSchema: z.ZodType<
  GetWalletSummaryResponse$Outbound,
  z.ZodTypeDef,
  GetWalletSummaryResponse
> = z.object({
  contentType: z.string(),
  getWalletSummaryResponse: shared.GetWalletSummaryResponse$outboundSchema
    .optional(),
  statusCode: z.number().int(),
  rawResponse: z.instanceof(Response).transform(() => {
    throw new Error("Response cannot be serialized");
  }),
}).transform((v) => {
  return remap$(v, {
    contentType: "ContentType",
    getWalletSummaryResponse: "GetWalletSummaryResponse",
    statusCode: "StatusCode",
    rawResponse: "RawResponse",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetWalletSummaryResponse$ {
  /** @deprecated use `GetWalletSummaryResponse$inboundSchema` instead. */
  export const inboundSchema = GetWalletSummaryResponse$inboundSchema;
  /** @deprecated use `GetWalletSummaryResponse$outboundSchema` instead. */
  export const outboundSchema = GetWalletSummaryResponse$outboundSchema;
  /** @deprecated use `GetWalletSummaryResponse$Outbound` instead. */
  export type Outbound = GetWalletSummaryResponse$Outbound;
}

export function getWalletSummaryResponseToJSON(
  getWalletSummaryResponse: GetWalletSummaryResponse,
): string {
  return JSON.stringify(
    GetWalletSummaryResponse$outboundSchema.parse(getWalletSummaryResponse),
  );
}

export function getWalletSummaryResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetWalletSummaryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetWalletSummaryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetWalletSummaryResponse' from JSON`,
  );
}
