/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../../lib/primitives";
import * as shared from "../shared";
import * as z from "zod";

export type ListWalletsRequest = {
    /**
     * Parameter used in pagination requests.
     *
     * @remarks
     * Set to the value of next for the next page of results.
     * Set to the value of previous for the previous page of results.
     * No other parameters can be set when the pagination token is set.
     *
     */
    cursor?: string | undefined;
    /**
     * Filter wallets by metadata key value pairs. Nested objects can be used as seen in the example below.
     */
    metadata?: { [k: string]: string } | undefined;
    /**
     * Filter on wallet name
     */
    name?: string | undefined;
    /**
     * The maximum number of results to return per page
     */
    pageSize?: number | undefined;
};

export type ListWalletsResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * OK
     */
    listWalletsResponse?: shared.ListWalletsResponse | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace ListWalletsRequest$ {
    export const inboundSchema: z.ZodType<ListWalletsRequest, z.ZodTypeDef, unknown> = z.object({
        cursor: z.string().optional(),
        metadata: z.record(z.string()).optional(),
        name: z.string().optional(),
        pageSize: z.number().int().default(15),
    });

    export type Outbound = {
        cursor?: string | undefined;
        metadata?: { [k: string]: string } | undefined;
        name?: string | undefined;
        pageSize: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListWalletsRequest> = z.object({
        cursor: z.string().optional(),
        metadata: z.record(z.string()).optional(),
        name: z.string().optional(),
        pageSize: z.number().int().default(15),
    });
}

/** @internal */
export namespace ListWalletsResponse$ {
    export const inboundSchema: z.ZodType<ListWalletsResponse, z.ZodTypeDef, unknown> = z
        .object({
            ContentType: z.string(),
            ListWalletsResponse: shared.ListWalletsResponse$.inboundSchema.optional(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return remap$(v, {
                ContentType: "contentType",
                ListWalletsResponse: "listWalletsResponse",
                StatusCode: "statusCode",
                RawResponse: "rawResponse",
            });
        });

    export type Outbound = {
        ContentType: string;
        ListWalletsResponse?: shared.ListWalletsResponse$.Outbound | undefined;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ListWalletsResponse> = z
        .object({
            contentType: z.string(),
            listWalletsResponse: shared.ListWalletsResponse$.outboundSchema.optional(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return remap$(v, {
                contentType: "ContentType",
                listWalletsResponse: "ListWalletsResponse",
                statusCode: "StatusCode",
                rawResponse: "RawResponse",
            });
        });
}
