/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type ListBankAccountsRequest = {
  /**
   * Parameter used in pagination requests. Maximum page size is set to 15.
   *
   * @remarks
   * Set to the value of next for the next page of results.
   * Set to the value of previous for the previous page of results.
   * No other parameters can be set when this parameter is set.
   */
  cursor?: string | undefined;
  /**
   * The maximum number of results to return per page.
   *
   * @remarks
   */
  pageSize?: number | undefined;
  /**
   * Fields used to sort payments (default is date:desc).
   */
  sort?: Array<string> | undefined;
};

export type ListBankAccountsResponse = {
  /**
   * OK
   */
  bankAccountsCursor?: shared.BankAccountsCursor | undefined;
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
};

/** @internal */
export type ListBankAccountsRequest$Outbound = {
  cursor?: string | undefined;
  pageSize: number;
  sort?: Array<string> | undefined;
};

/** @internal */
export const ListBankAccountsRequest$outboundSchema: z.ZodType<
  ListBankAccountsRequest$Outbound,
  z.ZodTypeDef,
  ListBankAccountsRequest
> = z.object({
  cursor: z.string().optional(),
  pageSize: z.number().int().default(15),
  sort: z.array(z.string()).optional(),
});

export function listBankAccountsRequestToJSON(
  listBankAccountsRequest: ListBankAccountsRequest,
): string {
  return JSON.stringify(
    ListBankAccountsRequest$outboundSchema.parse(listBankAccountsRequest),
  );
}

/** @internal */
export const ListBankAccountsResponse$inboundSchema: z.ZodType<
  ListBankAccountsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  BankAccountsCursor: shared.BankAccountsCursor$inboundSchema.optional(),
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
}).transform((v) => {
  return remap$(v, {
    "BankAccountsCursor": "bankAccountsCursor",
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

export function listBankAccountsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListBankAccountsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListBankAccountsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListBankAccountsResponse' from JSON`,
  );
}
