/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type ListBalancesRequest = {
  id: string;
};

export type ListBalancesResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * Balances list
   */
  listBalancesResponse?: shared.ListBalancesResponse | undefined;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
};

/** @internal */
export type ListBalancesRequest$Outbound = {
  id: string;
};

/** @internal */
export const ListBalancesRequest$outboundSchema: z.ZodType<
  ListBalancesRequest$Outbound,
  z.ZodTypeDef,
  ListBalancesRequest
> = z.object({
  id: z.string(),
});

export function listBalancesRequestToJSON(
  listBalancesRequest: ListBalancesRequest,
): string {
  return JSON.stringify(
    ListBalancesRequest$outboundSchema.parse(listBalancesRequest),
  );
}

/** @internal */
export const ListBalancesResponse$inboundSchema: z.ZodType<
  ListBalancesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  ListBalancesResponse: shared.ListBalancesResponse$inboundSchema.optional(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "ListBalancesResponse": "listBalancesResponse",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

export function listBalancesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListBalancesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListBalancesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListBalancesResponse' from JSON`,
  );
}
