/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import * as shared from "../shared/index.js";

export type ResetConnectorV1Request = {
  /**
   * The name of the connector.
   */
  connector: shared.Connector;
  /**
   * The connector ID.
   */
  connectorId: string;
};

export type ResetConnectorV1Response = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
};

/** @internal */
export const ResetConnectorV1Request$inboundSchema: z.ZodType<
  ResetConnectorV1Request,
  z.ZodTypeDef,
  unknown
> = z.object({
  connector: shared.Connector$inboundSchema,
  connectorId: z.string(),
});

/** @internal */
export type ResetConnectorV1Request$Outbound = {
  connector: string;
  connectorId: string;
};

/** @internal */
export const ResetConnectorV1Request$outboundSchema: z.ZodType<
  ResetConnectorV1Request$Outbound,
  z.ZodTypeDef,
  ResetConnectorV1Request
> = z.object({
  connector: shared.Connector$outboundSchema,
  connectorId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ResetConnectorV1Request$ {
  /** @deprecated use `ResetConnectorV1Request$inboundSchema` instead. */
  export const inboundSchema = ResetConnectorV1Request$inboundSchema;
  /** @deprecated use `ResetConnectorV1Request$outboundSchema` instead. */
  export const outboundSchema = ResetConnectorV1Request$outboundSchema;
  /** @deprecated use `ResetConnectorV1Request$Outbound` instead. */
  export type Outbound = ResetConnectorV1Request$Outbound;
}

/** @internal */
export const ResetConnectorV1Response$inboundSchema: z.ZodType<
  ResetConnectorV1Response,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

/** @internal */
export type ResetConnectorV1Response$Outbound = {
  ContentType: string;
  StatusCode: number;
  RawResponse: never;
};

/** @internal */
export const ResetConnectorV1Response$outboundSchema: z.ZodType<
  ResetConnectorV1Response$Outbound,
  z.ZodTypeDef,
  ResetConnectorV1Response
> = z.object({
  contentType: z.string(),
  statusCode: z.number().int(),
  rawResponse: z.instanceof(Response).transform(() => {
    throw new Error("Response cannot be serialized");
  }),
}).transform((v) => {
  return remap$(v, {
    contentType: "ContentType",
    statusCode: "StatusCode",
    rawResponse: "RawResponse",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ResetConnectorV1Response$ {
  /** @deprecated use `ResetConnectorV1Response$inboundSchema` instead. */
  export const inboundSchema = ResetConnectorV1Response$inboundSchema;
  /** @deprecated use `ResetConnectorV1Response$outboundSchema` instead. */
  export const outboundSchema = ResetConnectorV1Response$outboundSchema;
  /** @deprecated use `ResetConnectorV1Response$Outbound` instead. */
  export type Outbound = ResetConnectorV1Response$Outbound;
}
