/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type UpdateClientRequest = {
  createClientRequest?: shared.CreateClientRequest | undefined;
  /**
   * Client ID
   */
  clientId: string;
};

export type UpdateClientResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * Updated client
   */
  updateClientResponse?: shared.UpdateClientResponse | undefined;
};

/** @internal */
export type UpdateClientRequest$Outbound = {
  CreateClientRequest?: shared.CreateClientRequest$Outbound | undefined;
  clientId: string;
};

/** @internal */
export const UpdateClientRequest$outboundSchema: z.ZodType<
  UpdateClientRequest$Outbound,
  z.ZodTypeDef,
  UpdateClientRequest
> = z.object({
  createClientRequest: shared.CreateClientRequest$outboundSchema.optional(),
  clientId: z.string(),
}).transform((v) => {
  return remap$(v, {
    createClientRequest: "CreateClientRequest",
  });
});

export function updateClientRequestToJSON(
  updateClientRequest: UpdateClientRequest,
): string {
  return JSON.stringify(
    UpdateClientRequest$outboundSchema.parse(updateClientRequest),
  );
}

/** @internal */
export const UpdateClientResponse$inboundSchema: z.ZodType<
  UpdateClientResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  UpdateClientResponse: shared.UpdateClientResponse$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
    "UpdateClientResponse": "updateClientResponse",
  });
});

export function updateClientResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateClientResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateClientResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateClientResponse' from JSON`,
  );
}
