/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../../lib/primitives";
import * as shared from "../shared";
import * as z from "zod";

export type V2CreateLedgerRequest = {
    v2CreateLedgerRequest?: shared.V2CreateLedgerRequest | undefined;
    /**
     * Name of the ledger.
     */
    ledger: string;
};

export type V2CreateLedgerResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace V2CreateLedgerRequest$ {
    export const inboundSchema: z.ZodType<V2CreateLedgerRequest, z.ZodTypeDef, unknown> = z
        .object({
            V2CreateLedgerRequest: shared.V2CreateLedgerRequest$.inboundSchema.optional(),
            ledger: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                V2CreateLedgerRequest: "v2CreateLedgerRequest",
            });
        });

    export type Outbound = {
        V2CreateLedgerRequest?: shared.V2CreateLedgerRequest$.Outbound | undefined;
        ledger: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, V2CreateLedgerRequest> = z
        .object({
            v2CreateLedgerRequest: shared.V2CreateLedgerRequest$.outboundSchema.optional(),
            ledger: z.string(),
        })
        .transform((v) => {
            return remap$(v, {
                v2CreateLedgerRequest: "V2CreateLedgerRequest",
            });
        });
}

/** @internal */
export namespace V2CreateLedgerResponse$ {
    export const inboundSchema: z.ZodType<V2CreateLedgerResponse, z.ZodTypeDef, unknown> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return remap$(v, {
                ContentType: "contentType",
                StatusCode: "statusCode",
                RawResponse: "rawResponse",
            });
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, V2CreateLedgerResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return remap$(v, {
                contentType: "ContentType",
                statusCode: "StatusCode",
                rawResponse: "RawResponse",
            });
        });
}
