/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../../lib/primitives";
import * as shared from "../shared";
import * as z from "zod";

export type V2ListInstancesRequest = {
    /**
     * Parameter used in pagination requests.
     *
     * @remarks
     * Set to the value of next for the next page of results.
     * Set to the value of previous for the previous page of results.
     * No other parameters can be set when this parameter is set.
     *
     */
    cursor?: string | undefined;
    /**
     * The maximum number of results to return per page.
     *
     * @remarks
     *
     */
    pageSize?: number | undefined;
    /**
     * Filter running instances
     */
    running?: boolean | undefined;
    /**
     * A workflow id
     */
    workflowID?: string | undefined;
};

export type V2ListInstancesResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
    /**
     * List of workflow instances
     */
    v2ListRunsResponse?: shared.V2ListRunsResponse | undefined;
};

/** @internal */
export namespace V2ListInstancesRequest$ {
    export const inboundSchema: z.ZodType<V2ListInstancesRequest, z.ZodTypeDef, unknown> = z.object(
        {
            cursor: z.string().optional(),
            pageSize: z.number().int().optional(),
            running: z.boolean().optional(),
            workflowID: z.string().optional(),
        }
    );

    export type Outbound = {
        cursor?: string | undefined;
        pageSize?: number | undefined;
        running?: boolean | undefined;
        workflowID?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, V2ListInstancesRequest> =
        z.object({
            cursor: z.string().optional(),
            pageSize: z.number().int().optional(),
            running: z.boolean().optional(),
            workflowID: z.string().optional(),
        });
}

/** @internal */
export namespace V2ListInstancesResponse$ {
    export const inboundSchema: z.ZodType<V2ListInstancesResponse, z.ZodTypeDef, unknown> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
            V2ListRunsResponse: shared.V2ListRunsResponse$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                ContentType: "contentType",
                StatusCode: "statusCode",
                RawResponse: "rawResponse",
                V2ListRunsResponse: "v2ListRunsResponse",
            });
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
        V2ListRunsResponse?: shared.V2ListRunsResponse$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, V2ListInstancesResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
            v2ListRunsResponse: shared.V2ListRunsResponse$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                contentType: "ContentType",
                statusCode: "StatusCode",
                rawResponse: "RawResponse",
                v2ListRunsResponse: "V2ListRunsResponse",
            });
        });
}
