/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type V2RunQueryRequestBody = {
  cursor?: string | undefined;
  params?: shared.V2QueryParams | undefined;
  vars?: { [k: string]: string } | undefined;
};

/**
 * Deprecated: Use sort param
 */
export enum V2RunQueryOrder {
  Effective = "effective",
}

export type V2RunQueryRequest = {
  requestBody: V2RunQueryRequestBody;
  /**
   * Parameter used in pagination requests. Maximum page size is set to 15.
   *
   * @remarks
   * Set to the value of next for the next page of results.
   * Set to the value of previous for the previous page of results.
   * No other parameters can be set when this parameter is set.
   */
  cursor?: string | undefined;
  expand?: string | undefined;
  /**
   * Query template ID.
   */
  id: string;
  /**
   * Name of the ledger.
   */
  ledger: string;
  /**
   * Deprecated: Use sort param
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  order?: V2RunQueryOrder | undefined;
  /**
   * The maximum number of results to return per page.
   *
   * @remarks
   */
  pageSize?: number | undefined;
  pit?: Date | undefined;
  reverse?: boolean | undefined;
  /**
   * Schema version to use for validation
   */
  schemaVersion: string;
  /**
   * Sort results using a field name and order (ascending or descending).
   *
   * @remarks
   * Format: `<field>:<order>`, where `<field>` is the field name and `<order>` is either `asc` or `desc`.
   */
  sort?: string | undefined;
};

/**
 * OK
 */
export type V2RunQueryResponseBody =
  | shared.V2TransactionsCursorResponse
  | shared.V2AccountsCursorResponse
  | shared.V2LogsCursorResponse
  | shared.V2VolumesWithBalanceCursorResponse;

export type V2RunQueryResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * OK
   */
  oneOf?:
    | shared.V2TransactionsCursorResponse
    | shared.V2AccountsCursorResponse
    | shared.V2LogsCursorResponse
    | shared.V2VolumesWithBalanceCursorResponse
    | undefined;
};

/** @internal */
export type V2RunQueryRequestBody$Outbound = {
  cursor?: string | undefined;
  params?: shared.V2QueryParams$Outbound | undefined;
  vars?: { [k: string]: string } | undefined;
};

/** @internal */
export const V2RunQueryRequestBody$outboundSchema: z.ZodType<
  V2RunQueryRequestBody$Outbound,
  z.ZodTypeDef,
  V2RunQueryRequestBody
> = z.object({
  cursor: z.string().optional(),
  params: shared.V2QueryParams$outboundSchema.optional(),
  vars: z.record(z.string()).optional(),
});

export function v2RunQueryRequestBodyToJSON(
  v2RunQueryRequestBody: V2RunQueryRequestBody,
): string {
  return JSON.stringify(
    V2RunQueryRequestBody$outboundSchema.parse(v2RunQueryRequestBody),
  );
}

/** @internal */
export const V2RunQueryOrder$outboundSchema: z.ZodNativeEnum<
  typeof V2RunQueryOrder
> = z.nativeEnum(V2RunQueryOrder);

/** @internal */
export type V2RunQueryRequest$Outbound = {
  RequestBody: V2RunQueryRequestBody$Outbound;
  cursor?: string | undefined;
  expand?: string | undefined;
  id: string;
  ledger: string;
  order?: string | undefined;
  pageSize?: number | undefined;
  pit?: string | undefined;
  reverse?: boolean | undefined;
  schemaVersion: string;
  sort?: string | undefined;
};

/** @internal */
export const V2RunQueryRequest$outboundSchema: z.ZodType<
  V2RunQueryRequest$Outbound,
  z.ZodTypeDef,
  V2RunQueryRequest
> = z.object({
  requestBody: z.lazy(() => V2RunQueryRequestBody$outboundSchema),
  cursor: z.string().optional(),
  expand: z.string().optional(),
  id: z.string(),
  ledger: z.string(),
  order: V2RunQueryOrder$outboundSchema.optional(),
  pageSize: z.number().int().optional(),
  pit: z.date().transform(v => v.toISOString()).optional(),
  reverse: z.boolean().optional(),
  schemaVersion: z.string(),
  sort: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function v2RunQueryRequestToJSON(
  v2RunQueryRequest: V2RunQueryRequest,
): string {
  return JSON.stringify(
    V2RunQueryRequest$outboundSchema.parse(v2RunQueryRequest),
  );
}

/** @internal */
export const V2RunQueryResponseBody$inboundSchema: z.ZodType<
  V2RunQueryResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  shared.V2TransactionsCursorResponse$inboundSchema,
  shared.V2AccountsCursorResponse$inboundSchema,
  shared.V2LogsCursorResponse$inboundSchema,
  shared.V2VolumesWithBalanceCursorResponse$inboundSchema,
]);

export function v2RunQueryResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<V2RunQueryResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V2RunQueryResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V2RunQueryResponseBody' from JSON`,
  );
}

/** @internal */
export const V2RunQueryResponse$inboundSchema: z.ZodType<
  V2RunQueryResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
  oneOf: z.union([
    shared.V2TransactionsCursorResponse$inboundSchema,
    shared.V2AccountsCursorResponse$inboundSchema,
    shared.V2LogsCursorResponse$inboundSchema,
    shared.V2VolumesWithBalanceCursorResponse$inboundSchema,
  ]).optional(),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

export function v2RunQueryResponseFromJSON(
  jsonString: string,
): SafeParseResult<V2RunQueryResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V2RunQueryResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V2RunQueryResponse' from JSON`,
  );
}
