/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V2StartPipelineRequest = {
  /**
   * Name of the ledger.
   */
  ledger: string;
  /**
   * The pipeline id
   */
  pipelineID: string;
};

export type V2StartPipelineResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
};

/** @internal */
export type V2StartPipelineRequest$Outbound = {
  ledger: string;
  pipelineID: string;
};

/** @internal */
export const V2StartPipelineRequest$outboundSchema: z.ZodType<
  V2StartPipelineRequest$Outbound,
  z.ZodTypeDef,
  V2StartPipelineRequest
> = z.object({
  ledger: z.string(),
  pipelineID: z.string(),
});

export function v2StartPipelineRequestToJSON(
  v2StartPipelineRequest: V2StartPipelineRequest,
): string {
  return JSON.stringify(
    V2StartPipelineRequest$outboundSchema.parse(v2StartPipelineRequest),
  );
}

/** @internal */
export const V2StartPipelineResponse$inboundSchema: z.ZodType<
  V2StartPipelineResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

export function v2StartPipelineResponseFromJSON(
  jsonString: string,
): SafeParseResult<V2StartPipelineResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V2StartPipelineResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V2StartPipelineResponse' from JSON`,
  );
}
