/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V3AddAccountToPoolRequest = {
  /**
   * The account ID
   */
  accountID: string;
  /**
   * The pool ID
   */
  poolID: string;
};

export type V3AddAccountToPoolResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
};

/** @internal */
export const V3AddAccountToPoolRequest$inboundSchema: z.ZodType<
  V3AddAccountToPoolRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  accountID: z.string(),
  poolID: z.string(),
});

/** @internal */
export type V3AddAccountToPoolRequest$Outbound = {
  accountID: string;
  poolID: string;
};

/** @internal */
export const V3AddAccountToPoolRequest$outboundSchema: z.ZodType<
  V3AddAccountToPoolRequest$Outbound,
  z.ZodTypeDef,
  V3AddAccountToPoolRequest
> = z.object({
  accountID: z.string(),
  poolID: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3AddAccountToPoolRequest$ {
  /** @deprecated use `V3AddAccountToPoolRequest$inboundSchema` instead. */
  export const inboundSchema = V3AddAccountToPoolRequest$inboundSchema;
  /** @deprecated use `V3AddAccountToPoolRequest$outboundSchema` instead. */
  export const outboundSchema = V3AddAccountToPoolRequest$outboundSchema;
  /** @deprecated use `V3AddAccountToPoolRequest$Outbound` instead. */
  export type Outbound = V3AddAccountToPoolRequest$Outbound;
}

export function v3AddAccountToPoolRequestToJSON(
  v3AddAccountToPoolRequest: V3AddAccountToPoolRequest,
): string {
  return JSON.stringify(
    V3AddAccountToPoolRequest$outboundSchema.parse(v3AddAccountToPoolRequest),
  );
}

export function v3AddAccountToPoolRequestFromJSON(
  jsonString: string,
): SafeParseResult<V3AddAccountToPoolRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3AddAccountToPoolRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3AddAccountToPoolRequest' from JSON`,
  );
}

/** @internal */
export const V3AddAccountToPoolResponse$inboundSchema: z.ZodType<
  V3AddAccountToPoolResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  StatusCode: z.number().int(),
  RawResponse: z.instanceof(Response),
}).transform((v) => {
  return remap$(v, {
    "ContentType": "contentType",
    "StatusCode": "statusCode",
    "RawResponse": "rawResponse",
  });
});

/** @internal */
export type V3AddAccountToPoolResponse$Outbound = {
  ContentType: string;
  StatusCode: number;
  RawResponse: never;
};

/** @internal */
export const V3AddAccountToPoolResponse$outboundSchema: z.ZodType<
  V3AddAccountToPoolResponse$Outbound,
  z.ZodTypeDef,
  V3AddAccountToPoolResponse
> = z.object({
  contentType: z.string(),
  statusCode: z.number().int(),
  rawResponse: z.instanceof(Response).transform(() => {
    throw new Error("Response cannot be serialized");
  }),
}).transform((v) => {
  return remap$(v, {
    contentType: "ContentType",
    statusCode: "StatusCode",
    rawResponse: "RawResponse",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V3AddAccountToPoolResponse$ {
  /** @deprecated use `V3AddAccountToPoolResponse$inboundSchema` instead. */
  export const inboundSchema = V3AddAccountToPoolResponse$inboundSchema;
  /** @deprecated use `V3AddAccountToPoolResponse$outboundSchema` instead. */
  export const outboundSchema = V3AddAccountToPoolResponse$outboundSchema;
  /** @deprecated use `V3AddAccountToPoolResponse$Outbound` instead. */
  export type Outbound = V3AddAccountToPoolResponse$Outbound;
}

export function v3AddAccountToPoolResponseToJSON(
  v3AddAccountToPoolResponse: V3AddAccountToPoolResponse,
): string {
  return JSON.stringify(
    V3AddAccountToPoolResponse$outboundSchema.parse(v3AddAccountToPoolResponse),
  );
}

export function v3AddAccountToPoolResponseFromJSON(
  jsonString: string,
): SafeParseResult<V3AddAccountToPoolResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V3AddAccountToPoolResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V3AddAccountToPoolResponse' from JSON`,
  );
}
