/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as shared from "../shared/index.js";

export type V3ListPaymentServiceUserConnectionsFromConnectorIDRequest = {
  /**
   * The connector ID
   */
  connectorID: string;
  /**
   * Parameter used in pagination requests. Set to the value of next for the next page of results. Set to the value of previous for the previous page of results. No other parameters can be set when this parameter is set.
   *
   * @remarks
   */
  cursor?: string | undefined;
  /**
   * The number of items to return
   */
  pageSize?: number | undefined;
  /**
   * The payment service user ID
   */
  paymentServiceUserID: string;
};

export type V3ListPaymentServiceUserConnectionsFromConnectorIDResponse = {
  /**
   * HTTP response content type for this operation
   */
  contentType: string;
  /**
   * HTTP response status code for this operation
   */
  statusCode: number;
  /**
   * Raw HTTP response; suitable for custom response parsing
   */
  rawResponse: Response;
  /**
   * OK
   */
  v3PaymentServiceUserConnectionsCursorResponse?:
    | shared.V3PaymentServiceUserConnectionsCursorResponse
    | undefined;
};

/** @internal */
export type V3ListPaymentServiceUserConnectionsFromConnectorIDRequest$Outbound =
  {
    connectorID: string;
    cursor?: string | undefined;
    pageSize?: number | undefined;
    paymentServiceUserID: string;
  };

/** @internal */
export const V3ListPaymentServiceUserConnectionsFromConnectorIDRequest$outboundSchema:
  z.ZodType<
    V3ListPaymentServiceUserConnectionsFromConnectorIDRequest$Outbound,
    z.ZodTypeDef,
    V3ListPaymentServiceUserConnectionsFromConnectorIDRequest
  > = z.object({
    connectorID: z.string(),
    cursor: z.string().optional(),
    pageSize: z.number().int().optional(),
    paymentServiceUserID: z.string(),
  });

export function v3ListPaymentServiceUserConnectionsFromConnectorIDRequestToJSON(
  v3ListPaymentServiceUserConnectionsFromConnectorIDRequest:
    V3ListPaymentServiceUserConnectionsFromConnectorIDRequest,
): string {
  return JSON.stringify(
    V3ListPaymentServiceUserConnectionsFromConnectorIDRequest$outboundSchema
      .parse(v3ListPaymentServiceUserConnectionsFromConnectorIDRequest),
  );
}

/** @internal */
export const V3ListPaymentServiceUserConnectionsFromConnectorIDResponse$inboundSchema:
  z.ZodType<
    V3ListPaymentServiceUserConnectionsFromConnectorIDResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    ContentType: z.string(),
    StatusCode: z.number().int(),
    RawResponse: z.instanceof(Response),
    V3PaymentServiceUserConnectionsCursorResponse: shared
      .V3PaymentServiceUserConnectionsCursorResponse$inboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      "ContentType": "contentType",
      "StatusCode": "statusCode",
      "RawResponse": "rawResponse",
      "V3PaymentServiceUserConnectionsCursorResponse":
        "v3PaymentServiceUserConnectionsCursorResponse",
    });
  });

export function v3ListPaymentServiceUserConnectionsFromConnectorIDResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  V3ListPaymentServiceUserConnectionsFromConnectorIDResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V3ListPaymentServiceUserConnectionsFromConnectorIDResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'V3ListPaymentServiceUserConnectionsFromConnectorIDResponse' from JSON`,
  );
}
