/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { SDKBaseError } from "../errors/sdkbaseerror.js";

export enum ErrorCode {
  Validation = "VALIDATION",
  InternalError = "INTERNAL_ERROR",
  InsufficientFund = "INSUFFICIENT_FUND",
  HoldClosed = "HOLD_CLOSED",
}

export type ErrorResponseData = {
  errorCode: ErrorCode;
  errorMessage: string;
};

export class ErrorResponse extends SDKBaseError {
  errorCode: ErrorCode;
  errorMessage: string;

  /** The original data that was passed to this error instance. */
  data$: ErrorResponseData;

  constructor(
    err: ErrorResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.errorCode = err.errorCode;
    this.errorMessage = err.errorMessage;

    this.name = "ErrorResponse";
  }
}

/** @internal */
export const ErrorCode$inboundSchema: z.ZodNativeEnum<typeof ErrorCode> = z
  .nativeEnum(ErrorCode);

/** @internal */
export const ErrorResponse$inboundSchema: z.ZodType<
  ErrorResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  errorCode: ErrorCode$inboundSchema,
  errorMessage: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new ErrorResponse(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
