/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { WalletsV1 } from "./walletsv1.js";

export class Wallets extends ClientSDK {
  private _v1?: WalletsV1;
  get v1(): WalletsV1 {
    return (this._v1 ??= new WalletsV1(this._options));
  }
}
