/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import {
  V2BulkElementAddMetadata,
  V2BulkElementAddMetadata$Outbound,
  V2BulkElementAddMetadata$outboundSchema,
} from "./v2bulkelementaddmetadata.js";
import {
  V2BulkElementCreateTransaction,
  V2BulkElementCreateTransaction$Outbound,
  V2BulkElementCreateTransaction$outboundSchema,
} from "./v2bulkelementcreatetransaction.js";
import {
  V2BulkElementDeleteMetadata,
  V2BulkElementDeleteMetadata$Outbound,
  V2BulkElementDeleteMetadata$outboundSchema,
} from "./v2bulkelementdeletemetadata.js";
import {
  V2BulkElementRevertTransaction,
  V2BulkElementRevertTransaction$Outbound,
  V2BulkElementRevertTransaction$outboundSchema,
} from "./v2bulkelementreverttransaction.js";

export type V2BulkElement =
  | V2BulkElementAddMetadata
  | V2BulkElementCreateTransaction
  | V2BulkElementDeleteMetadata
  | V2BulkElementRevertTransaction;

/** @internal */
export type V2BulkElement$Outbound =
  | V2BulkElementAddMetadata$Outbound
  | V2BulkElementCreateTransaction$Outbound
  | V2BulkElementDeleteMetadata$Outbound
  | V2BulkElementRevertTransaction$Outbound;

/** @internal */
export const V2BulkElement$outboundSchema: z.ZodType<
  V2BulkElement$Outbound,
  z.ZodTypeDef,
  V2BulkElement
> = z.union([
  V2BulkElementAddMetadata$outboundSchema,
  V2BulkElementCreateTransaction$outboundSchema,
  V2BulkElementDeleteMetadata$outboundSchema,
  V2BulkElementRevertTransaction$outboundSchema,
]);

export function v2BulkElementToJSON(v2BulkElement: V2BulkElement): string {
  return JSON.stringify(V2BulkElement$outboundSchema.parse(v2BulkElement));
}
