/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../../lib/primitives.js";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  V2BulkElementResult,
  V2BulkElementResult$inboundSchema,
} from "./v2bulkelementresult.js";
import { V2ErrorsEnum, V2ErrorsEnum$inboundSchema } from "./v2errorsenum.js";

export type V2BulkResponse = {
  v2ErrorsEnum?: V2ErrorsEnum | undefined;
  data?: Array<V2BulkElementResult> | undefined;
  errorMessage?: string | undefined;
};

/** @internal */
export const V2BulkResponse$inboundSchema: z.ZodType<
  V2BulkResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  errorCode: V2ErrorsEnum$inboundSchema.optional(),
  data: z.array(V2BulkElementResult$inboundSchema).optional(),
  errorMessage: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "errorCode": "v2ErrorsEnum",
  });
});

export function v2BulkResponseFromJSON(
  jsonString: string,
): SafeParseResult<V2BulkResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V2BulkResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V2BulkResponse' from JSON`,
  );
}
