/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { V2Log, V2Log$inboundSchema } from "./v2log.js";

export type V2LogsCursorResponseCursor = {
  data: Array<V2Log>;
  hasMore: boolean;
  next?: string | undefined;
  pageSize: number;
  previous?: string | undefined;
};

export enum V2LogsCursorResponseResource {
  Logs = "logs",
}

export type V2LogsCursorResponse = {
  cursor: V2LogsCursorResponseCursor;
  resource?: V2LogsCursorResponseResource | undefined;
};

/** @internal */
export const V2LogsCursorResponseCursor$inboundSchema: z.ZodType<
  V2LogsCursorResponseCursor,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(V2Log$inboundSchema),
  hasMore: z.boolean(),
  next: z.string().optional(),
  pageSize: z.number().int(),
  previous: z.string().optional(),
});

export function v2LogsCursorResponseCursorFromJSON(
  jsonString: string,
): SafeParseResult<V2LogsCursorResponseCursor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V2LogsCursorResponseCursor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V2LogsCursorResponseCursor' from JSON`,
  );
}

/** @internal */
export const V2LogsCursorResponseResource$inboundSchema: z.ZodNativeEnum<
  typeof V2LogsCursorResponseResource
> = z.nativeEnum(V2LogsCursorResponseResource);

/** @internal */
export const V2LogsCursorResponse$inboundSchema: z.ZodType<
  V2LogsCursorResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  cursor: z.lazy(() => V2LogsCursorResponseCursor$inboundSchema),
  resource: V2LogsCursorResponseResource$inboundSchema.optional(),
});

export function v2LogsCursorResponseFromJSON(
  jsonString: string,
): SafeParseResult<V2LogsCursorResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V2LogsCursorResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V2LogsCursorResponse' from JSON`,
  );
}
