// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type InsertConfigResponse struct {
	// Config created successfully.
	ConfigResponse *components.ConfigResponse
	HTTPMeta       components.HTTPMetadata `json:"-"`
}

func (o *InsertConfigResponse) GetConfigResponse() *components.ConfigResponse {
	if o == nil {
		return nil
	}
	return o.ConfigResponse
}

func (o *InsertConfigResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
