// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type V2DeleteAccountMetadataRequest struct {
	// Account address
	Address string `pathParam:"style=simple,explode=false,name=address"`
	// The key to remove.
	Key string `pathParam:"style=simple,explode=false,name=key"`
	// Name of the ledger.
	Ledger string `pathParam:"style=simple,explode=false,name=ledger"`
}

func (o *V2DeleteAccountMetadataRequest) GetAddress() string {
	if o == nil {
		return ""
	}
	return o.Address
}

func (o *V2DeleteAccountMetadataRequest) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}

func (o *V2DeleteAccountMetadataRequest) GetLedger() string {
	if o == nil {
		return ""
	}
	return o.Ledger
}

type V2DeleteAccountMetadataResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *V2DeleteAccountMetadataResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
