// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"mockserver/internal/sdk/models/components"
)

type V2GetInstanceStageHistoryRequest struct {
	// The instance id
	InstanceID string `pathParam:"style=simple,explode=false,name=instanceID"`
	// The stage number
	Number int64 `pathParam:"style=simple,explode=false,name=number"`
}

func (o *V2GetInstanceStageHistoryRequest) GetInstanceID() string {
	if o == nil {
		return ""
	}
	return o.InstanceID
}

func (o *V2GetInstanceStageHistoryRequest) GetNumber() int64 {
	if o == nil {
		return 0
	}
	return o.Number
}

type V2GetInstanceStageHistoryResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The workflow instance stage history
	V2GetWorkflowInstanceHistoryStageResponse *components.V2GetWorkflowInstanceHistoryStageResponse
}

func (o *V2GetInstanceStageHistoryResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *V2GetInstanceStageHistoryResponse) GetV2GetWorkflowInstanceHistoryStageResponse() *components.V2GetWorkflowInstanceHistoryStageResponse {
	if o == nil {
		return nil
	}
	return o.V2GetWorkflowInstanceHistoryStageResponse
}
