workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    stacks-source:
        inputs:
            - location: https://github.com/formancehq/stack/releases/download/v3.0.3/generate.json
        overlays:
            - location: ./overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/formance/formance/stacks-source
targets:
    formance-sdk-typescript:
        target: typescript
        source: stacks-source
        publish:
            npm:
                token: $NPM_TOKEN
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/formance/formance/stacks-source-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
        testing:
            enabled: false
