workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: https://github.com/formancehq/stack/releases/download/v2.1.0-beta.2/generate.json
        registry:
            location: registry.speakeasyapi.dev/formance/formance/my-source
targets:
    formance-sdk-typescript:
        target: typescript
        source: my-source
        publish:
            npm:
                token: $NPM_TOKEN
