/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ActivityGetPayment = {
  id: string;
};

/** @internal */
export const ActivityGetPayment$inboundSchema: z.ZodType<
  ActivityGetPayment,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

export function activityGetPaymentFromJSON(
  jsonString: string,
): SafeParseResult<ActivityGetPayment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ActivityGetPayment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ActivityGetPayment' from JSON`,
  );
}
