/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type StageSendSourceAccount = {
  /**
   * Enables unbounded overdraft on the throughAccount when set to true.
   *
   * @remarks
   * This is useful when the throughAccount represents a liability or bridge account
   * that needs to go negative (e.g., "liabilities:payouts-pending").
   * Only applies when throughAccount is not "world" (which already has unbounded overdraft).
   */
  allowOverdraft: boolean;
  id: string;
  ledger?: string | undefined;
  /**
   * Account used when this ledger account interacts with external systems (payments, cross-ledger).
   *
   * @remarks
   * - As SOURCE going to payment: funds are sent to this account (e.g., "liabilities:payouts-pending")
   * - As DESTINATION from payment: funds come from this account (e.g., "assets:stripe:incoming")
   * - For cross-ledger transfers: replaces "world" on both sides
   */
  throughAccount: string;
};

/** @internal */
export const StageSendSourceAccount$inboundSchema: z.ZodType<
  StageSendSourceAccount,
  z.ZodTypeDef,
  unknown
> = z.object({
  allowOverdraft: z.boolean().default(false),
  id: z.string(),
  ledger: z.string().optional(),
  throughAccount: z.string().default("world"),
});

export function stageSendSourceAccountFromJSON(
  jsonString: string,
): SafeParseResult<StageSendSourceAccount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StageSendSourceAccount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StageSendSourceAccount' from JSON`,
  );
}
