/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type TriggerData1 = {
  createdAt: Date;
  event: string;
  filter?: string | undefined;
  id: string;
  name?: string | undefined;
  vars?: { [k: string]: any } | undefined;
  version?: string | undefined;
  workflowID: string;
};

/** @internal */
export const TriggerData1$inboundSchema: z.ZodType<
  TriggerData1,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  event: z.string(),
  filter: z.string().optional(),
  id: z.string(),
  name: z.string().optional(),
  vars: z.record(z.any()).optional(),
  version: z.string().optional(),
  workflowID: z.string(),
});

export function triggerData1FromJSON(
  jsonString: string,
): SafeParseResult<TriggerData1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TriggerData1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TriggerData1' from JSON`,
  );
}
