/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { UpdateAccount, UpdateAccount$inboundSchema } from "./updateaccount.js";

export type Update = {
  account?: UpdateAccount | undefined;
};

/** @internal */
export const Update$inboundSchema: z.ZodType<Update, z.ZodTypeDef, unknown> = z
  .object({
    account: UpdateAccount$inboundSchema.optional(),
  });

export function updateFromJSON(
  jsonString: string,
): SafeParseResult<Update, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Update$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Update' from JSON`,
  );
}
