/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V2ActivityVoidHold = {
  id: string;
};

/** @internal */
export const V2ActivityVoidHold$inboundSchema: z.ZodType<
  V2ActivityVoidHold,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

export function v2ActivityVoidHoldFromJSON(
  jsonString: string,
): SafeParseResult<V2ActivityVoidHold, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V2ActivityVoidHold$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V2ActivityVoidHold' from JSON`,
  );
}
