// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type ListRunsResponse struct {
	Data []WorkflowInstance `json:"data"`
}

func (o *ListRunsResponse) GetData() []WorkflowInstance {
	if o == nil {
		return []WorkflowInstance{}
	}
	return o.Data
}
