// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type V3PoolsCursorResponseCursor struct {
	Data     []V3Pool `json:"data"`
	HasMore  bool     `json:"hasMore"`
	Next     *string  `json:"next,omitempty"`
	PageSize int64    `json:"pageSize"`
	Previous *string  `json:"previous,omitempty"`
}

func (o *V3PoolsCursorResponseCursor) GetData() []V3Pool {
	if o == nil {
		return []V3Pool{}
	}
	return o.Data
}

func (o *V3PoolsCursorResponseCursor) GetHasMore() bool {
	if o == nil {
		return false
	}
	return o.HasMore
}

func (o *V3PoolsCursorResponseCursor) GetNext() *string {
	if o == nil {
		return nil
	}
	return o.Next
}

func (o *V3PoolsCursorResponseCursor) GetPageSize() int64 {
	if o == nil {
		return 0
	}
	return o.PageSize
}

func (o *V3PoolsCursorResponseCursor) GetPrevious() *string {
	if o == nil {
		return nil
	}
	return o.Previous
}

type V3PoolsCursorResponse struct {
	Cursor V3PoolsCursorResponseCursor `json:"cursor"`
}

func (o *V3PoolsCursorResponse) GetCursor() V3PoolsCursorResponseCursor {
	if o == nil {
		return V3PoolsCursorResponseCursor{}
	}
	return o.Cursor
}
