// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type WorkflowConfig struct {
	Name   *string          `json:"name,omitempty"`
	Stages []map[string]any `json:"stages"`
}

func (o *WorkflowConfig) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *WorkflowConfig) GetStages() []map[string]any {
	if o == nil {
		return []map[string]any{}
	}
	return o.Stages
}
